[package]
name = "felics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
num = "0.4.1"
bitstream-io = "2.2.0"
byteorder = "1.5.0"

[dev-dependencies]
rand = "0.8.5"
